FROM nginx:stable-alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /usr/share/nginx/html/index.html
COPY style-includes.html /usr/share/nginx/html/style-includes.html
COPY style.css /usr/share/nginx/html/style.css

EXPOSE 80

